# netlify.toml

# This block tells Netlify to automatically install dependencies 
# found in the package.json file located inside your functions directory.
[[plugins]]
package = "@netlify/plugin-functions-install-core"
